#ifndef _CONFIG_H
#define _CONFIG_H

#define BATTERY_VOLTAGE_SENSOR false
#define BATTERY_LATCH 0.05
#define BATTERY_VOLTAGE_LOW 3.45
#define BATTERY_VOLTAGE_CRITICAL 3.33
#define BATTERY_VOLTAGE_SHUTDOWN 3.25

#define PATTERN_BANK_SIZE 5
#define PATTERN_BANK_COUNT 3

#define DEFAULT_PINOUT_VARIANT 1
#define DEFAULT_LED_TYPE 1
#define DEFAULT_LED_COUNT 15

#endif // _CONFIG_H