enum CommCode {
  success, // 0
  error, // 1
  setBrightness, // 2
  setSpeed, // 3
  setPattern, // 4
  setPatternSlot, // 5
  setPatternAll, // 6
  setBank, // 7
  setBankAll, // 8
  getFwVersion, // 9
  setHardwareVersion, // 10
  setLedType, // 11
  setLedCount, // 12
  setDeviceName, // 13
  setSequencer, // 14
  startSequencer, // 15
  setBrightnessOption, // 16
  setBrightnessOptions, // 17
  setSpeedOption, // 18
  setSpeedOptions, // 19
  setPatternShuffleDuration, // 20
}
